name: Daily Business News Email

on:
  schedule:
    - cron: '35 01 * * *'  # Runs at 6:30 PM BD Time (12:30 UTC)
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scripts
        run: |
          python tesla_news.py
          python business_news.py
          python entertainment_news.py
          python tech_news.py
          python wallstreet_news.py
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.APP_PASS }}
