name: Daily Business News Email

on:
  schedule:
    - cron: '30 12 * * *'  
  workflow_dispatch:      # allows manual run from GitHub interface

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python tesla_news.py
             python business_news.py
             python entertainment_news.py
             python tech_news.py
             python wallstreet_news.py

